from typing import Annotated, overload

import numpy
from numpy.typing import NDArray
import scipy.sparse


class SolverBase:
    def set_num_threads(self, arg: int, /) -> None: ...

    def num_threads(self) -> int: ...

    def set_device(self, arg: str, /) -> None: ...

    def device(self) -> str: ...

    def set_tol(self, arg: float, /) -> None: ...

    def tol(self) -> float: ...

    def set_max_iterations(self, arg: int, /) -> None: ...

    def max_iterations(self) -> int: ...

class CGSolverCore(SolverBase):
    def __init__(self, num_threads: int = 0, device: str = 'cpu', tol: float = 1e-06, max_iterations: int = 0) -> None: ...

    def solve(self, A: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], b: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], x0: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')] | None = None, tol: float | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

class BiCGStabSolverCore(SolverBase):
    def __init__(self, num_threads: int = 0, device: str = 'cpu', tol: float = 1e-06, max_iterations: int = 0) -> None: ...

    def solve(self, A: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], b: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], x0: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')] | None = None, tol: float | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

class LSCGSolverCore(SolverBase):
    def __init__(self, num_threads: int = 0, device: str = 'cpu', tol: float = 1e-06, max_iterations: int = 0) -> None: ...

    def solve(self, A: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], b: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], x0: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')] | None = None, tol: float | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

class ILUCGSolverCore(SolverBase):
    def __init__(self, num_threads: int = 0, device: str = 'cpu', tol: float = 1e-06, max_iterations: int = 0) -> None: ...

    def solve(self, A: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], b: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], x0: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')] | None = None, tol: float | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    def solve_sparse(self, A: scipy.sparse.csc_matrix[float], b: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], x0: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')] | None = None, tol: float | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

class ILUBiCGStabSolverCore(SolverBase):
    def __init__(self, num_threads: int = 0, device: str = 'cpu', tol: float = 1e-06, max_iterations: int = 0) -> None: ...

    def solve(self, A: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], b: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], x0: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')] | None = None, tol: float | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    def solve_sparse(self, A: scipy.sparse.csc_matrix[float], b: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], x0: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')] | None = None, tol: float | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

class ILULSCGSolverCore(SolverBase):
    def __init__(self, num_threads: int = 0, device: str = 'cpu', tol: float = 1e-06, max_iterations: int = 0) -> None: ...

    def solve(self, A: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], b: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], x0: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')] | None = None, tol: float | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    def solve_sparse(self, A: scipy.sparse.csc_matrix[float], b: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], x0: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')] | None = None, tol: float | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

@overload
def solve_cg(A: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], b: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], x0: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')] | None = None, tol: float = 1e-06) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

@overload
def solve_cg(A: Annotated[NDArray[numpy.complex128], dict(shape=(None, None), order='C')], b: Annotated[NDArray[numpy.complex128], dict(shape=(None,), order='C')], x0: Annotated[NDArray[numpy.complex128], dict(shape=(None,), order='C')] | None = None, tol: float = 1e-06) -> Annotated[NDArray[numpy.complex128], dict(shape=(None,), order='C')]: ...

@overload
def solve_bicgstab(A: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], b: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], x0: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')] | None = None, tol: float = 1e-06) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

@overload
def solve_bicgstab(A: Annotated[NDArray[numpy.complex128], dict(shape=(None, None), order='C')], b: Annotated[NDArray[numpy.complex128], dict(shape=(None,), order='C')], x0: Annotated[NDArray[numpy.complex128], dict(shape=(None,), order='C')] | None = None, tol: float = 1e-06) -> Annotated[NDArray[numpy.complex128], dict(shape=(None,), order='C')]: ...

@overload
def solve_lscg(A: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], b: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], x0: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')] | None = None, tol: float = 1e-06) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

@overload
def solve_lscg(A: Annotated[NDArray[numpy.complex128], dict(shape=(None, None), order='C')], b: Annotated[NDArray[numpy.complex128], dict(shape=(None,), order='C')], x0: Annotated[NDArray[numpy.complex128], dict(shape=(None,), order='C')] | None = None, tol: float = 1e-06) -> Annotated[NDArray[numpy.complex128], dict(shape=(None,), order='C')]: ...

@overload
def solve_cg_ilu(A: scipy.sparse.csc_matrix[float], b: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], x0: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')] | None = None, tol: float = 1e-06) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

@overload
def solve_cg_ilu(A: scipy.sparse.csc_matrix["std::complex<double>"], b: Annotated[NDArray[numpy.complex128], dict(shape=(None,), order='C')], x0: Annotated[NDArray[numpy.complex128], dict(shape=(None,), order='C')] | None = None, tol: float = 1e-06) -> Annotated[NDArray[numpy.complex128], dict(shape=(None,), order='C')]: ...

@overload
def solve_bicgstab_ilu(A: scipy.sparse.csc_matrix[float], b: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], x0: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')] | None = None, tol: float = 1e-06) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

@overload
def solve_bicgstab_ilu(A: scipy.sparse.csc_matrix["std::complex<double>"], b: Annotated[NDArray[numpy.complex128], dict(shape=(None,), order='C')], x0: Annotated[NDArray[numpy.complex128], dict(shape=(None,), order='C')] | None = None, tol: float = 1e-06) -> Annotated[NDArray[numpy.complex128], dict(shape=(None,), order='C')]: ...

@overload
def solve_lscg_ilu(A: scipy.sparse.csc_matrix[float], b: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], x0: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')] | None = None, tol: float = 1e-06) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

@overload
def solve_lscg_ilu(A: scipy.sparse.csc_matrix["std::complex<double>"], b: Annotated[NDArray[numpy.complex128], dict(shape=(None,), order='C')], x0: Annotated[NDArray[numpy.complex128], dict(shape=(None,), order='C')] | None = None, tol: float = 1e-06) -> Annotated[NDArray[numpy.complex128], dict(shape=(None,), order='C')]: ...

@overload
def solve_full_piv_lu(A: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], b: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

@overload
def solve_full_piv_lu(A: Annotated[NDArray[numpy.complex128], dict(shape=(None, None), order='C')], b: Annotated[NDArray[numpy.complex128], dict(shape=(None,), order='C')]) -> Annotated[NDArray[numpy.complex128], dict(shape=(None,), order='C')]: ...

@overload
def solve_partial_piv_lu(A: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], b: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

@overload
def solve_partial_piv_lu(A: Annotated[NDArray[numpy.complex128], dict(shape=(None, None), order='C')], b: Annotated[NDArray[numpy.complex128], dict(shape=(None,), order='C')]) -> Annotated[NDArray[numpy.complex128], dict(shape=(None,), order='C')]: ...

class NNPreprocessor:
    def __init__(self, model_path: str, device: str = 'auto') -> None: ...

    def predict(self, A: scipy.sparse.csc_matrix["std::complex<double>"], b: Annotated[NDArray[numpy.complex128], dict(shape=(None, None), order='C')]) -> Annotated[NDArray[numpy.complex128], dict(shape=(None, None), order='C')]: ...
